export enum AlertType {
  NONE = 'NONE',
  HEAT_WAVE = 'HEAT_WAVE',
  FROST = 'FROST',
  STORM = 'STORM',
  EXTREME_HEAT = "EXTREME_HEAT",
  LOW_PRESSURE = "LOW_PRESSURE",
  HIGH_HUMIDITY = "HIGH_HUMIDITY"
}